module: src.client.agents.HTTPAgent
parameters:
  url: http://localhost:11436/v1/chat/completions
  headers:
    Content-Type: application/json
  body:
    model: google/gemma-3-12b-it
    temperature: 0
    max_tokens: 2048
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
